### ISSUE TITLE
[Exception Handling] 클래스로서 존재하지 않는 차종을 입력할 때의 예외처리

### ISSUE THREAD

**Issue by S0YKIM** [S0YKIM/Java-design-pattern#1]
- 원래 과제에서는 if~else~ 조건문을 통해 입력 받은 차종류가 어떤 클래스에도 일치하지 않는 경우 "noname" 이라는 이름을 가진 차 인스턴스를 생성
- 하지만 애초에 그러한 차 종류가 존재하지 않으면 생성조차 되지 않는 것이 옳다고 판단,
- CarTypeNotFoundException 이라는 예외 클래스를 만들어 throw 하도록 리팩토링

**Comment by anso33** [comment]
- 지정된 이름외의 다른 이름이 들어왔을 때 Noname이라는 클래스를 만들어 받도록 했는데 Noname이라는 car를 상속받는 클래스가 존재한다는 것이 부자연스럽게 느껴짐. sokim님과의 대화를 통해 위와 같은 경우 에러처리 하는 것이 더 자연스럽겠다고 결론을 내림.
