### ISSUE TITLE
[Singleton] 인스턴스 객체의 null 여부를 확인하는 코드의 필요성?

### ISSUE THREAD

**Issue by S0YKIM** [S0YKIM/Java-design-pattern#2]
```
if(instance == null) {
    instance = new Singleton();
}
```

- 위의 코드가 없어도 정상 작동하는데 꼭 필요한 것인지
- 필요하다면 어떤 경우를 방지하기 위해서인지
- 인스턴스를 생성하려는데 힙 메모리 공간이 부족해서 생성에 실패한 경우?
- 만약에 그렇다고 하면 다시 생성을 시도하는게 아니라 예외 처리를 하는게 맞다고 생각(throw exception)

**Comment by S0YKIM** [comment]
#3

**Comment by S0YKIM** [comment]
- 위의 방법이 클래스 로딩 시점이 아닌 인스턴스가 요청될 때 생성되는 Lazy init 방법이라는 것을 깨달았는데
- 그렇다면 기존의 코드에서 맨 앞에 인스턴스 생성하는 부분을 제거하는 것이 맞다고 본다
```
// 기존 코드
 private static Singleton instance = new Singleton();
```

```
// 변경 코드
private static Singleton instance;
```

**Comment by S0YKIM** [comment]
#4

**Comment by anso33** [comment]
- sokim님을 통해서 클래스 안에서 미리 객체를 생성하여 사용하는 방법과 외부에서 생성한 뒤 getInstance()함수에서 객체 변수에 대한 null을 확인하는 방법, 2가지 방법이 있음을 배웠다. 

- 0727 전체 세미나에서 발표를 통해 이외에도 synchronized를 사용한 2가지 방법이 더 있음을 배웠다.
